server:
  port: 8080

spring:
  application:
    name: exam-system-online-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_exam_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  data:
    redis:
      host: 192.168.27.104
      port: 6379
      database: 0
      password:
      timeout: 3000ms
exam:
  status:
    update-interval: 60s
    initial-delay: 10s

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.exam.online.dal.dataobject

logging:
  level:
    root: info

rocketmq:
  name-server: 192.168.27.104:9876
  producer:
    group: exam-producer-group
  answer:
    topic: exam-answer-save
    consumer-group: exam-answer-consumer-group

